name: TestWorkflow

on:
  workflow_dispatch:
  push:
    branches:
      - main
  
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
        dotnet-version: ['8.0.x', '9.0.x']
    
    runs-on: ${{ matrix.os }}
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: runner context
        run: echo '${{ toJSON(runner) }}'

      - name: skriv github context
        run: echo '${{ toJSON(github) }}'

      - name: Setup .NET ${{ matrix.dotnet-version }}
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: ${{ matrix.dotnet-version }}
        
      - name: Build
        run: dotnet build

      - name: Run tests
        if: success()
        run: dotnet test

      - name: push info 
        if: github.event.name == 'push'
        run: |
          echo "=============="
          echo "Message: ${{ github.event.head_commit.message}}"
          echo "Author: ${{ github.event.head_commit.author.name}}"
          echo "Committer ${{github.event.head_commit.commiter.name}}"
          echo "Branch ${{github.ref_name}}"
          echo "=============="

  
  

    
